export { User, type IUser } from './models/User';
export { Stage, type IStage, DEFAULT_STAGES } from './models/Stage';
export { Product, type IProduct, SAMPLE_PRODUCTS } from './models/Product';
export { Lead, type ILead, getNextLeadNumber } from './models/Lead';
export { Interaction, type IInteraction } from './models/Interaction';
export { Deal, type IDeal } from './models/Deal';
export { Task, type ITask } from './models/Task';
export { WAConversation, WAMessage, type IWAConversation, type IWAMessage } from './models/WhatsAppModels';
export { Campaign, WorkflowRule, type ICampaign, type IWorkflowRule } from './models/Campaign';
export { connectDB } from './connection';
